annotations:
    screwdriver.cd/chainPR: true

jobs:
  first:
    requires: [ ~pr, ~commit ]
    image: node:12
    steps:
      - echo: ls
  second:
    requires: first
    image: node:12
    steps:
      - echo: echo second job
